# this is a configuration template for pauls-desk.  Copy this file to ./config.yml and populate with variables for your environment
#

base_url:       https://cloud.skytap.com                                # base url for rest queries
token:          <api_token>                                             # API Token

working_dir:    <path to skynet.py>                                     # this is the path to the skynet.py file
temp_dir:       <path to temp directory>                                # path to a temporary directory

